language: python

python:
  - '2.5'
  - '2.6'
  - '2.7'
  - 'pypy'

install:
  - pip install tox>=1.8

env:
  - DB=sqlite:memory
  - DB=mysql://root:@localhost/pydal
  - DB=postgres://postgres:@localhost/pydal
  - DB=google:datastore
  - DB=mongodb://localhost/pydal
  - DB=imap://imap:imap@localhost:993

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install unittest2; fi
  - if [[ $DB == postgres* ]]; then pip install psycopg2; fi;
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install pysqlite; fi
  - if [[ $DB == mysql* ]]; then mysql -e 'create database pydal;'; fi
  - if [[ $DB == postgres* ]]; then psql -c 'create database pydal;' -U postgres; fi
  - if [[ $DB == postgres* ]]; then psql -c 'create extension postgis;' -U postgres -d pydal; fi

  # Install last sdk for app engine (update only whenever a new release is available)
  - if [[ $DB == google* ]]; then wget http://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv; fi
  - if [[ $DB == google* ]]; then unzip -q google_appengine_1.8.9.zip; fi
  - if [[ $DB == google* ]]; then mv -f ./google_appengine/google ./google; fi

  # Install pymongo
  - if [[ $DB == mongodb* ]]; then pip install pymongo; fi
  #- if [[ $DB == mongodb* ]]; then mongo pydal --eval "db.addUser('mongodb', 'mongodb');"; fi

matrix:
  exclude:
    - python: 'pypy'
      env: DB=postgres://postgres:@localhost/pydal
    - python: 'pypy'
      env: DB=mysql://root:@localhost/pydal
    - python: 'pypy'
      env: DB=google:datastore
    - python: '2.5'
      env: DB=google:datastore
    - python: '2.6'
      env: DB=google:datastore

notifications:
  email: false

services: mongodb
